### ISSUE TITLE
No Module found named Selenium

### ISSUE THREAD

**Issue by aterriblegamer** [niamu/palpable#2]
Running the command

>./audible-activator.py -h

I get this error

Traceback (most recent call last):
  File "./audible-activator.py", line 8, in <module>
    from selenium import webdriver
ImportError: No module named selenium

I did install Selenium

>pip install selenium
Requirement already satisfied: selenium in /Library/Python/2.7/site-packages/selenium-3.8.1-py2.7.egg

Any idea why I would get this error?

I am running on MacOS Sierra

**Comment by niamu** [comment]
This issue isn't really related to this project, but I see that the author of [audible-activator](https://github.com/inAudible-NG/audible-activator) has disabled their issues section, so I'll help you out.

Based on your report I can't understand why you'd be having issues. I'd double check to make sure that you're running `audible-activator.py` with Python 2 and not Python 3.

If you still can't work it out, try giving [audible-activator-robobrowser](https://github.com/pkillnine/audible-activator-robobrowser) a shot.

**Comment by aterriblegamer** [comment]
I am running 2.7. I don't even have 3 installed. I will try this other one. Thank you for helping! Your project is the one I have been looking for forever!

**Comment by aterriblegamer** [comment]
Installed version 3, Attempted to use that robobrowsker project. That one fails with an error attempting to log into audible. Ug!

**Comment by niamu** [comment]
Sorry to hear that. I hope you work it out. Perhaps try on another machine or a fresh virtual machine. I just confirmed that audible-activator works for me still without issue.

Finally, you can give the [RainbowCrack plugin](https://github.com/inAudible-NG/tables) a try. I haven't used it yet myself, but it would certainly avoid the Python issues you're having.
