### ISSUE TITLE
Execute docker, getting errors after downloading files

### ISSUE THREAD

**Issue by aterriblegamer** [niamu/palpable#3]
Finally got the activation bytes!

I have run the docker image. I checked back in after it was running for awhile and there were no files in the clean folder.

I have 3 books downloaded to /sources/. 
It did add the correct .png alongside there .aax in /sources.

When I scrolled up through the buffer I saw two things I thought might be an issue

1)  Message that activation_bytes option is missing. 

Does this mean my activation bytes data in the config.edn is not being picked up?

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  372M  100  372M    0     0  1071k      0  0:05:56  0:05:56 --:--:-- 1076k
ffmpeg version 3.2.10-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5574bb5aeda0] [aax] file checksum == b7a4db930c438eaf49c705d7aaaab881fc164a4b
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5574bb5aeda0] [aax] activation_bytes option is missing!

2) After a bunch of data about the chapters I saw this error.

Open: open(resources/clean/AUTHOR/TITLE.m4b) failed (src/mp4file.cpp,398)
ERROR: unable to open for write: resources/clean/AUTHOR/TITLE.m4b

It would then proceed to download the next file, and give the same error.

**Comment by niamu** [comment]
I'm assuming you didn't have a file named exactly "config.edn" with your activation bytes in it in the resources folder at the time the Docker image was built.

The script is fairly straightforward, so I doubt there's an issue on my end. I just tie together existing tools.

You can always just run the ffmpeg command manually:

`ffmpeg -activation_bytes XXXXX -i input.aax -c:a copy -vn -f mp4 output.m4b`

It is difficult to understand what exactly is going wrong without seeing much more information which the Docker container that I made for convenience doesn't make easy.

The next thing to look at would be the generated file in the Docker container under `script/download.sh`. That file will pinpoint either missing activation bytes as a result of a misconfiguration on your part or a bug in my script generation. If you identify it is a script issue on my part, please leave a detailed description with what is wrong and I will address it.

If you happen to solve it on your own, please close this issue with your fix so future users can benefit.

**Comment by aterriblegamer** [comment]
I cleaned everything up just to make sure.
Rebuilt the container. I grabbed the download.sh and it does have the activation_bytes in the file

Here is an example

mkdir -p "resources/sources/Mark Twain/";
mkdir -p "resources/clean/Mark Twain/";
curl "http://cds.audible.com/download?<PERSONAL_USER_INFO_REMOVED>" -o "resources/sources/Mark Twain/""A Connecticut Yankee in King Arthur's Court".aax;
ffmpeg -i "resources/sources/Mark Twain/""A Connecticut Yankee in King Arthur's Court".aax "resources/sources/Mark Twain/""A Connecticut Yankee in King Arthur's Court".png;
ffmpeg -activation_bytes <MY_BYTES_HERE> -i "resources/sources/Mark Twain/""A Connecticut Yankee in King Arthur's Court".aax -c:a copy -vn -f mp4"resources/clean/Mark Twain/""A Connecticut Yankee in King Arthur's Court".m4b;
mp4art --add "resources/sources/Mark Twain/""A Connecticut Yankee in King Arthur's Court".png "resources/clean/Mark Twain/""A Connecticut Yankee in King Arthur's Court".m4b

I tried to run the following ffmpeg command (I updated the paths for outside the container)

ffmpeg -activation_bytes MY_BYTES -i "/Users/plex/Downloads/palpable-master/resources/sources/Orson Scott Card/""Children of the Fleet".aax -c:a copy -vn -f mp4"/Users/plex/Downloads/palpable-master/resources/clean/Orson Scott Card/""Children of the Fleet".m4b;

And this is what I got: (Bold sections were highlighted in the terminal output)

ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
**Trailing options were found on the commandline.**
**[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff088802600] [aax] file checksum == b7a4db930c438eaf49c705d7aaaab881fc164a4b
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff088802600] stream 0, timescale not set**
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/plex/Downloads/palpable-master/resources/sources/Orson Scott Card/Children of the Fleet.aax':
  Metadata:
    major_brand     : aax 
    minor_version   : 1
    compatible_brands: aax M4B mp42isom
    creation_time   : 2018-02-04T18:18:55.000000Z
    genre           : Audiobook
    title           : Children of the Fleet (Unabridged)
    artist          : Orson Scott  Card
    album_artist    : Orson Scott  Card
    album           : Children of the Fleet (Unabridged)
    comment         : Ender Wiggin won the Third Formic war, ending the alien threat to Earth. Afterwards, all the terraformed Formic worlds were open to settlement by humans, and the International Fleet....
    copyright       : &#169;2017 Orson Scott Card ;(P)2017 Macmillan Audio
    date            : 2017
  Duration: 11:37:47.51, start: 0.000000, bitrate: 5 kb/s
    Chapter #0:0: start 0.000000, end 1347.593288
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 1347.593288, end 3581.167166
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 3581.167166, end 5928.379501
    Metadata:
      title           : 
    Chapter #0:3: start 5928.379501, end 7678.513923
    Metadata:
      title           : 
    Chapter #0:4: start 7678.513923, end 9450.846621
    Metadata:
      title           : 
    Chapter #0:5: start 9450.846621, end 10650.575238
    Metadata:
      title           : 
    Chapter #0:6: start 10650.575238, end 13401.025306
    Metadata:
      title           : 
    Chapter #0:7: start 13401.025306, end 15716.565624
    Metadata:
      title           : 
    Chapter #0:8: start 15716.565624, end 17774.782404
    Metadata:
      title           : 
    Chapter #0:9: start 17774.782404, end 19944.408526
    Metadata:
      title           : 
    Chapter #0:10: start 19944.408526, end 22124.437188
    Metadata:
      title           : 
    Chapter #0:11: start 22124.437188, end 24918.958730
    Metadata:
      title           : 
    Chapter #0:12: start 24918.958730, end 27184.204626
    Metadata:
      title           : 
    Chapter #0:13: start 27184.204626, end 29785.954104
    Metadata:
      title           : 
    Chapter #0:14: start 29785.954104, end 32661.466848
    Metadata:
      title           : 
    Chapter #0:15: start 32661.466848, end 34213.070658
    Metadata:
      title           : 
    Chapter #0:16: start 34213.070658, end 37589.995102
    Metadata:
      title           : 
    Chapter #0:17: start 37589.995102, end 40165.273832
    Metadata:
      title           : 
    Chapter #0:18: start 40165.273832, end 41867.513333
    Metadata:
      title           : 
    Stream #0:0(eng): Audio: aac (LC) (aavd / 0x64766161), 22050 Hz, stereo, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2018-02-04T18:18:55.000000Z
      handler_name    : ?Apple Sound Media Handler
    Stream #0:1(eng): Data: bin_data (text / 0x74786574) (default)
    Metadata:
      creation_time   : 2018-02-04T18:18:58.000000Z
      handler_name    : ?Apple Text Media Handler
    Stream #0:2: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
**At least one output file must be specified**

**Comment by niamu** [comment]
There was a missing space in the generated download script. I've pushed a fix now with the latest commit: b459920

That should resolve the issues reported here. Let me know if it helps.

**Comment by aterriblegamer** [comment]
I just figured that out too! Thank you for the update!
