### ISSUE TITLE
Issue with the html file created from Audible

### ISSUE THREAD

**Issue by aterriblegamer** [niamu/palpable#4]
I have about 300 title in my library.

I log into the my books page. Set the filter to All Time and set the display to the max (200 per page)

I save that page as library.html

I open the library.html file and it does not display with the options I had selected before the save. The page is set to last 6 months and 20 per page.

This limits me to about 14 titles.

I thought I could just save multiple pages and run through my library in chunks. However it doesn't save being on another page properly either. It always saves with the default page settings.

**Comment by niamu** [comment]
You have to save the generated HTML of the page and not the page itself. This is different in every browser, but I'm sure you'll work it out.

This isn't an issue on my part. Please don't open issues unrelated to the project.

**Comment by aterriblegamer** [comment]
I have been able to grab the first 200 books, but can't seem to get the next 100. I'll see if I can figure out a strategy. I tried going to page 2 and doing save as in Chrome like I did for page 1. However when Open it the file it still shows page 1.
