### ISSUE TITLE
Error executing docker image with latest build

### ISSUE THREAD

**Issue by aterriblegamer** [niamu/palpable#5]
With the latest change I am now getting an error running the docker image after the build.

Mini:palpable plex$ docker run \
>     --rm -it \
>     -v $(pwd)/resources:/usr/src/palpable/resources \
>     palpable
Retrieving hickory/hickory/0.7.1/hickory-0.7.1.pom from clojars
Retrieving org/clojure/clojurescript/1.9.293/clojurescript-1.9.293.pom from central
Retrieving com/google/javascript/closure-compiler-unshaded/v20160911/closure-compiler-unshaded-v20160911.pom from central
Retrieving com/google/javascript/closure-compiler-main/v20160911/closure-compiler-main-v20160911.pom from central
Retrieving com/google/javascript/closure-compiler-parent/v20160911/closure-compiler-parent-v20160911.pom from central
Retrieving org/sonatype/oss/oss-parent/9/oss-parent-9.pom from central
Retrieving com/google/javascript/closure-compiler-externs/v20160911/closure-compiler-externs-v20160911.pom from central
Retrieving args4j/args4j/2.0.26/args4j-2.0.26.pom from central
Retrieving args4j/args4j-site/2.0.26/args4j-site-2.0.26.pom from central
Retrieving org/kohsuke/pom/6/pom-6.pom from central
Retrieving com/google/guava/guava/19.0/guava-19.0.pom from central
Retrieving com/google/guava/guava-parent/19.0/guava-parent-19.0.pom from central
Retrieving com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.pom from central
Retrieving com/google/google/1/google-1.pom from central
Retrieving com/google/code/gson/gson/2.2.4/gson-2.2.4.pom from central
Retrieving com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom from central
Retrieving com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotations-1.0.0.pom from central
Retrieving com/google/jsinterop/jsinterop/1.0.0/jsinterop-1.0.0.pom from central
Retrieving org/sonatype/oss/oss-parent/4/oss-parent-4.pom from central
Retrieving org/clojure/google-closure-library/0.0-20160609-f42b4a24/google-closure-library-0.0-20160609-f42b4a24.pom from central
Retrieving org/clojure/google-closure-library-third-party/0.0-20160609-f42b4a24/google-closure-library-third-party-0.0-20160609-f42b4a24.pom from central
Retrieving org/clojure/data.json/0.2.6/data.json-0.2.6.pom from central
Retrieving org/clojure/clojure/1.4.0/clojure-1.4.0.pom from central
Retrieving org/sonatype/oss/oss-parent/5/oss-parent-5.pom from central
Retrieving org/mozilla/rhino/1.7R5/rhino-1.7R5.pom from central
Retrieving org/clojure/tools.reader/1.0.0-beta3/tools.reader-1.0.0-beta3.pom from central
Retrieving org/clojure/clojure/1.5.1/clojure-1.5.1.pom from central
Retrieving org/jsoup/jsoup/1.9.2/jsoup-1.9.2.pom from central
Retrieving viebel/codox-klipse-theme/0.0.1/codox-klipse-theme-0.0.1.pom from clojars
Retrieving quoin/quoin/0.1.2/quoin-0.1.2.pom from clojars
Retrieving args4j/args4j/2.0.26/args4j-2.0.26.jar from central
Retrieving org/clojure/clojurescript/1.9.293/clojurescript-1.9.293.jar from central
Retrieving com/google/javascript/closure-compiler-externs/v20160911/closure-compiler-externs-v20160911.jar from central
Retrieving com/google/javascript/closure-compiler-unshaded/v20160911/closure-compiler-unshaded-v20160911.jar from central
Retrieving com/google/guava/guava/19.0/guava-19.0.jar from central
Retrieving com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar from central
Retrieving com/google/code/gson/gson/2.2.4/gson-2.2.4.jar from central
Retrieving com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar from central
Retrieving com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotations-1.0.0.jar from central
Retrieving org/clojure/google-closure-library/0.0-20160609-f42b4a24/google-closure-library-0.0-20160609-f42b4a24.jar from central
Retrieving org/clojure/google-closure-library-third-party/0.0-20160609-f42b4a24/google-closure-library-third-party-0.0-20160609-f42b4a24.jar from central
Retrieving org/clojure/data.json/0.2.6/data.json-0.2.6.jar from central
Retrieving org/mozilla/rhino/1.7R5/rhino-1.7R5.jar from central
Retrieving org/clojure/tools.reader/1.0.0-beta3/tools.reader-1.0.0-beta3.jar from central
Retrieving org/jsoup/jsoup/1.9.2/jsoup-1.9.2.jar from central
Retrieving hickory/hickory/0.7.1/hickory-0.7.1.jar from clojars
Retrieving quoin/quoin/0.1.2/quoin-0.1.2.jar from clojars
Retrieving viebel/codox-klipse-theme/0.0.1/codox-klipse-theme-0.0.1.jar from clojars
Exception in thread "main" java.lang.IllegalArgumentException: No value supplied for key: n, compiling:(/tmp/form-init8321724145643451392.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No value supplied for key: n
	at clojure.lang.PersistentHashMap.create(PersistentHashMap.java:77)
	at clojure.core$hash_map.invokeStatic(core.clj:387)
	at clojure.core$hash_map.doInvoke(core.clj:379)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.java.io$writer.invokeStatic(io.clj:119)
	at clojure.java.io$writer.doInvoke(io.clj:104)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$spit.invokeStatic(core.clj:6668)
	at clojure.core$spit.doInvoke(core.clj:6668)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at palpable.core$_main.invokeStatic(core.cljc:57)
	at palpable.core$_main.doInvoke(core.cljc:54)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init8321724145643451392.clj:1)
	at user$eval5.invoke(form-init8321724145643451392.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more

**Comment by niamu** [comment]
Sorry. That was a typo on my part. I've amended the change. Clone the project fresh and try again.

**Comment by aterriblegamer** [comment]
The download doesn't appear to start now. I get a 46KB file in my sources folder

Retrieving viebel/codox-klipse-theme/0.0.1/codox-klipse-theme-0.0.1.jar from clojars
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    46  100    46    0     0    139      0 --:--:-- --:--:-- --:--:--   139
ffmpeg version 3.2.10-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
resources/sources/Mark Twain/A Connecticut Yankee in King Arthur's Court.aax: Invalid data found when processing input

**Comment by aterriblegamer** [comment]
This error seems to be specific to this file. I removed the code from the last commit that exits if an error occurs. The script was able to get past that file and continue. Processing many files now. 
Thank you for your great work.
